name: Tweet release

on: 
  release:
    types: [published]

jobs:
  tweet-release:
    runs-on: ubuntu-latest

    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: >
            ✨ I've just released ${{ github.event.release.tag_name }} of Color, my small PHP package for working with different colors.
            
            
            Check out the release notes here: https://github.com/ryangjchandler/color/releases/tag/${{ github.event.release.tag_name }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
